apiVersion: apps/v1
kind: Deployment
metadata:
  name: meuprimeirodeployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: exemplo 
  template:
    metadata:
      labels:
        app: exemplo
    spec:
      containers:
      - name: meucontainer
        image: kubedevio/nginx-color:green